spring:
  datasource:
    url: jdbc:sqlite:./doutor_ia.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        type:
          preferred_uuid_jdbc_type: varchar

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: 8080

gemini:
  api:
    key: ${GEMINI_API_KEY:}

upload:
  dir: ${UPLOAD_DIR:./uploads}
